# Contents is generated dynamically
version: '3.7'
services:
    app:
        container_name: example_app
        restart: unless-stopped
        build:
            args:
                PHP_VERSION: '8.2'
                NODE_VERSION: '20'
                ENVIRONMENT: development
            context: ./docker/php-fpm
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            XDEBUG_MODE: '${DOCKER_XDEBUG_MODE:-debug}'
            XDEBUG_CONFIG: '${DOCKER_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            TZ: '${TZ:-UTC}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - './:/var/www/html'
            - '${COMPOSER_HOME:-$HOME/.composer}:/var/www/.composer'
            - './storage/app/code-coverage:/opt/phpstorm-coverage'
        depends_on:
            - db
            - nginx
            - selenium
            - redis
            - redisinsight
            - meilisearch
        networks:
            - app-network
    db:
        image: 'mysql/mysql-server:8.0'
        container_name: example_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_TEST_DATABASE: '${DB_TEST_DATABASE:-${DB_DATABASE}_test}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            TZ: '${TZ:-UTC}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
            - './docker/mysql/my.cnf:/etc/my.cnf'
            - './docker/mysql/my.cnf.d/:/etc/my.cnf.d/'
        networks:
            - app-network
    nginx:
        image: 'nginx:alpine'
        container_name: example_nginx
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - app-network
    selenium:
        image: '${SELENIUM_IMAGE:-selenium/standalone-chrome}'
        container_name: example_selenium
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - app-network
    redis:
        image: 'redis:alpine'
        container_name: example_redis
        restart: unless-stopped
        volumes:
            - 'redis-data:/data'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - app-network
    redisinsight:
        image: 'redislabs/redisinsight:latest'
        container_name: example_redisinsight
        restart: unless-stopped
        volumes:
            - 'redisinsight-data:/db'
        ports:
            - '${FORWARD_REDISINSIGHT_PORT:-8001}:8001'
        networks:
            - app-network
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: example_meilisearch
        restart: unless-stopped
        volumes:
            - 'meilisearch-data:/meili_data'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        networks:
            - app-network
volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
    redisinsight-data:
        driver: local
    meilisearch-data:
        driver: local
networks:
    app-network:
        driver: bridge
