version: "3.7"
services:
  app:
    image: laravel-docker-app:%php_version%
    container_name: %slug%_app
    build:
      args:
        uid: %uid%
      context: ./docker/php-fpm
      dockerfile: dev.Dockerfile
    user: laravel
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - "${COMPOSER_HOME}:/home/%username%/.composer"
      #- './storage/app/code-coverage:/opt/phpstorm-coverage'
    depends_on:
      - db
      - nginx
    networks:
      - app-network

  db:
    image: mysql/mysql-server:8.0
    container_name: %slug%_db
    restart: "no"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TEST_DATABASE: ${DB_TEST_DATABASE:-"$DB_DATABASE"_test}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./docker/mysql/default.cnf:/etc/my.cnf.d/00-default.cnf
      - ./docker/mysql/optimize.cnf:/etc/my.cnf.d/01-optimize.cnf
      #- ./docker/mysql/import.cnf:/etc/my.cnf.d/02-import.cnf
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: %slug%_nginx
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  selenium:
    image: "${SELENIUM_IMAGE:-selenium/standalone-chrome}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
